# Generated by Django 5.2.14 on 2026-06-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_doctorprofile_address_doctorprofile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='momo_network',
            field=models.CharField(blank=True, default='MTN', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='momo_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
