# Generated by Django 5.2.14 on 2026-05-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_consultation_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('AUDIO', 'Audio'), ('IMAGE', 'Image')], default='TEXT', max_length=5),
        ),
    ]
